import requests
import urllib3
import json

# Suppresses Insecure request warnings generated by requests module
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

def handle(req):

    status = json.loads(req)

    url = "https://{}{}".format(status["hostname"], status["status_payload"]["executionStatusUrl"])
    payload = ""
    headers = {
        "Content-Type": "application/json",
        "x-auth-token": status["Token"]
        }

    validate = requests.request("GET", url, data=json.dumps(payload), headers=headers, verify=False)

    # print(validate.text)
    return validate.text